---
http:
  external:
    port: 3013
  internal:
    debug_endpoints: true
    port: 3113
    listen_address: 0.0.0.0
  endpoints:
    dry-run: true

websocket:
  channel:
    listen_address: 0.0.0.0
    port: 3014

chain:
  persist: true
  hard_forks:
    "1": 0
    "5": 1

fork_management:
  network_id: "ae_uat"
